name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install Maven wrapper
        run: mvn -N io.takari:maven:wrapper

      - name: Build with Maven
        run: ./mvnw clean install

      - name: Run unit tests
        run: ./mvnw test

      - name: Measure code coverage
        run: ./mvnw jacoco:report

      - name: Print code coverage report
        run: |
          coverage=$(grep -A 1 '<counter type="INSTRUCTION"' target/site/jacoco/jacoco.xml | tail -n 1 | awk -F'"' '{print $2}')
          total=$(grep -A 1 '<counter type="INSTRUCTION"' target/site/jacoco/jacoco.xml | tail -n 1 | awk -F'"' '{print $4}')
          percent=$(echo "scale=2; $coverage/$total*100" | bc)
          echo "Code coverage: $percent%"

      - name: Build Docker image
        run: docker build -t spring-boot-webapp .
